// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1oR8Bz_PmS_TOCi6s97sfILUkAcSPNs',
    appId: '1:940055187752:web:abca2b48d8f8bbcda7801d',
    messagingSenderId: '940055187752',
    projectId: 'c-and-f',
    authDomain: 'c-and-f.firebaseapp.com',
    databaseURL: 'https://c-and-f-default-rtdb.firebaseio.com',
    storageBucket: 'c-and-f.appspot.com',
    measurementId: 'G-ZNYDT14VD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPSj6jBJIg4c00-IfsvIOgB1_f-0EiJmY',
    appId: '1:940055187752:android:781e173510fd7546a7801d',
    messagingSenderId: '940055187752',
    projectId: 'c-and-f',
    databaseURL: 'https://c-and-f-default-rtdb.firebaseio.com',
    storageBucket: 'c-and-f.appspot.com',
  );
}
